"""
Cross-sectional dementia classification from sleep-derived features.

Reproduces the binary classification analyses from
    Ye et al., Dementia detection from brain activity during sleep,
    SLEEP 46(3):zsac286, 2023 (https://doi.org/10.1093/sleep/zsac286).

Three binary tasks are evaluated:
    DEM_vs_CN       — dementia at PSG vs. cognitively normal
    MCI_vs_CN       — MCI at PSG vs. cognitively normal
    DEMMCI_vs_CN    — DEM or MCI at PSG vs. CN

Three model families:
    LR   — L2-regularized logistic regression
    SVM  — radial-basis-function support vector machine
    RF   — random forest

Performance is estimated by stratified nested cross-validation: an outer K-fold
loop for unbiased AUROC/AUPRC and an inner K-fold loop for hyperparameter
selection. Bootstrap 95% confidence intervals are computed on the pooled outer
predictions.

Reproduction caveats — the original modeling script is not in any project
folder we have searched. The DEM/MCI/CN labels here are derived from the
prevalent-event flags in `mastersheet_outcome_deid.xlsx` (`cens_X == 1 AND
time_X <= 0`) — this is a rule-based proxy for the labels used in the paper,
which were generated by Elissa's chart-review criteria
(`code/01_phenotyping/step2b_*ElissaCriteria*.py`). Headline metrics from this
script should be compared to the paper's AUROC 0.78 / 0.73 / 0.76 to validate
that the proxy labels and feature matrix are aligned with the paper.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    average_precision_score,
    precision_recall_curve,
    roc_auc_score,
    roc_curve,
)
from sklearn.model_selection import GridSearchCV, StratifiedKFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC


# ---------- data ----------

# Columns in features_MGH_deid.csv that are not features (IDs, dates, label-leak risks).
ID_COLS = ["HashID", "DOVshifted"]


def load_data(features_csv: Path, mastersheet_xlsx: Path,
              labels_csv: Path | None = None) -> pd.DataFrame:
    """Join the deidentified feature matrix with outcome / label tables.

    `features_MGH_deid.csv` is keyed by `HashID`. `mastersheet_outcome_deid.xlsx`
    provides the `HashID ↔ BDSPPatientID` crosswalk plus survival outcomes for
    the SBOP cohort. `MGH_dementia_all_*_Elissa_rule_made_by_Haoqi.csv`, if
    supplied, provides BDSPPatientID-keyed dementia diagnosis dates which can
    be compared to PSG date (`DOVshifted`) to infer prevalent DEM at baseline.
    """
    feats = pd.read_csv(features_csv)
    outcomes = pd.read_excel(mastersheet_xlsx)
    df = feats.merge(
        outcomes[["HashID", "BDSPPatientID",
                  "cens_Dementia", "time_Dementia",
                  "cens_MCI+Dementia", "time_MCI+Dementia"]],
        on="HashID", how="inner",
    )
    if labels_csv is not None and labels_csv.exists():
        labels = pd.read_csv(labels_csv, parse_dates=["DiagnosisDate"])
        # Some patients have multiple diagnosis dates → keep the earliest.
        labels = (labels.sort_values("DiagnosisDate")
                        .drop_duplicates("BDSPPatientID", keep="first")
                        .rename(columns={"DiagnosisDate": "DementiaDxDate"}))
        df = df.merge(labels[["BDSPPatientID", "DementiaDxDate"]],
                      on="BDSPPatientID", how="left")
    else:
        df["DementiaDxDate"] = pd.NaT
    return df


def derive_labels(df: pd.DataFrame) -> pd.DataFrame:
    """Add a categorical `dx_baseline` column with values DEM / MCI / CN / OTHER.

    Logic
    -----
    The mastersheet uses the SAS-style censoring convention `cens_X == 1` means
    censored (no event) and `cens_X == 0` means event observed. All `time_X` in
    the SBOP mastersheet are non-negative — prevalent cases were filtered out
    of the SBOP survival cohort. Therefore prevalent DEM at PSG is inferred
    from the BDSP-deID dementia label table (`DementiaDxDate <= DOVshifted`)
    when available; otherwise the proxy falls back to the survival-derived
    "never any event" rule, which under-counts DEM at baseline.

    Definitions:
        DEM   — DementiaDxDate <= DOVshifted (prevalent dementia at PSG)
        MCI   — currently NOT separately identifiable from the deidentified
                tables we ship; flagged as `MCI?` so downstream code can drop
                them. The original paper's MCI labels live in the rule-based
                output of `code/01_phenotyping/step2b/c_*ElissaCriteria*.py`.
        CN    — no dementia in follow-up AND (no MCI in follow-up OR no MCI
                date available)
        OTHER — incident events post-PSG, ambiguous, or missing label info.
    """
    out = df.copy()
    out["dx_baseline"] = "OTHER"

    dov = pd.to_datetime(out["DOVshifted"], errors="coerce")
    dxd = pd.to_datetime(out["DementiaDxDate"], errors="coerce")

    prevalent_dem = dxd.notna() & (dxd <= dov)
    never_dem_or_mci = (out["cens_Dementia"] == 1) & (out["cens_MCI+Dementia"] == 1)
    incident_mci_only = (out["cens_Dementia"] == 1) & (out["cens_MCI+Dementia"] == 0)

    out.loc[never_dem_or_mci, "dx_baseline"] = "CN"
    out.loc[incident_mci_only, "dx_baseline"] = "MCI?"  # placeholder
    out.loc[prevalent_dem, "dx_baseline"] = "DEM"
    return out


def slice_for_task(df: pd.DataFrame, task: str) -> tuple[pd.DataFrame, np.ndarray]:
    if task == "DEM_vs_CN":
        sub = df[df["dx_baseline"].isin(["DEM", "CN"])].copy()
        y = (sub["dx_baseline"] == "DEM").astype(int).values
    elif task == "MCI_vs_CN":
        sub = df[df["dx_baseline"].isin(["MCI", "CN"])].copy()
        y = (sub["dx_baseline"] == "MCI").astype(int).values
    elif task == "DEMMCI_vs_CN":
        sub = df[df["dx_baseline"].isin(["DEM", "MCI", "CN"])].copy()
        y = sub["dx_baseline"].isin(["DEM", "MCI"]).astype(int).values
    else:
        raise ValueError(f"unknown task: {task}")
    return sub, y


def feature_matrix(df: pd.DataFrame) -> tuple[np.ndarray, list[str]]:
    """Drop ID and outcome columns; return (X, feature_names)."""
    drop = set(ID_COLS) | {
        "cens_Dementia", "time_Dementia",
        "cens_MCI+Dementia", "time_MCI+Dementia",
        "dx_baseline",
    }
    feat_cols = [c for c in df.columns if c not in drop]
    X = df[feat_cols].apply(pd.to_numeric, errors="coerce").values
    return X, feat_cols


# ---------- models ----------

def build_pipelines(numeric_features_n: int, random_state: int = 0):
    """Three (model_name, pipeline, param_grid) tuples."""
    pre_scaled = Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler()),
    ])
    pre_unscaled = Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
    ])

    lr = (
        "LR",
        Pipeline([("pre", pre_scaled),
                  ("clf", LogisticRegression(
                      penalty="l2", solver="liblinear",
                      class_weight="balanced", max_iter=1000,
                      random_state=random_state))]),
        {"clf__C": [0.01, 0.1, 1.0, 10.0]},
    )
    svm = (
        "SVM",
        Pipeline([("pre", pre_scaled),
                  ("clf", SVC(kernel="rbf", probability=True,
                              class_weight="balanced",
                              random_state=random_state))]),
        {"clf__C": [0.1, 1.0, 10.0], "clf__gamma": ["scale", 0.01, 0.001]},
    )
    rf = (
        "RF",
        Pipeline([("pre", pre_unscaled),
                  ("clf", RandomForestClassifier(
                      n_estimators=300, class_weight="balanced",
                      n_jobs=-1, random_state=random_state))]),
        {"clf__max_depth": [None, 6, 12], "clf__min_samples_leaf": [1, 5]},
    )
    return [lr, svm, rf]


# ---------- evaluation ----------

def bootstrap_ci(y_true, y_score, fn, n_boot=1000, seed=0, alpha=0.05):
    rng = np.random.default_rng(seed)
    n = len(y_true)
    stats = []
    for _ in range(n_boot):
        idx = rng.integers(0, n, n)
        if len(np.unique(y_true[idx])) < 2:  # skip degenerate resamples
            continue
        stats.append(fn(y_true[idx], y_score[idx]))
    lo, hi = np.quantile(stats, [alpha / 2, 1 - alpha / 2])
    return float(np.mean(stats)), float(lo), float(hi)


def evaluate_task(df, y, task, output_dir, *,
                  outer_k=5, inner_k=3, random_state=0, n_boot=1000):
    X, feat_cols = feature_matrix(df)
    print(f"  features: X.shape={X.shape}, n_pos={int(y.sum())}, "
          f"n_neg={int(len(y)-y.sum())}, prevalence={y.mean():.3f}")

    outer = StratifiedKFold(n_splits=outer_k, shuffle=True, random_state=random_state)
    pipelines = build_pipelines(X.shape[1], random_state=random_state)

    results = {}
    for name, pipe, grid in pipelines:
        oof = np.zeros(len(y), dtype=float)
        best_params = []
        for fold_i, (tr, te) in enumerate(outer.split(X, y)):
            inner = StratifiedKFold(n_splits=inner_k, shuffle=True,
                                    random_state=random_state + fold_i)
            search = GridSearchCV(pipe, grid, cv=inner,
                                  scoring="roc_auc", n_jobs=-1, refit=True)
            search.fit(X[tr], y[tr])
            oof[te] = search.predict_proba(X[te])[:, 1]
            best_params.append(search.best_params_)

        auroc, auroc_lo, auroc_hi = bootstrap_ci(
            y, oof, roc_auc_score, n_boot=n_boot, seed=random_state)
        auprc, auprc_lo, auprc_hi = bootstrap_ci(
            y, oof, average_precision_score, n_boot=n_boot, seed=random_state)
        results[name] = {
            "auroc": auroc, "auroc_ci": [auroc_lo, auroc_hi],
            "auprc": auprc, "auprc_ci": [auprc_lo, auprc_hi],
            "best_params_per_fold": best_params,
        }
        print(f"    {name:>3s}: AUROC={auroc:.3f} ({auroc_lo:.3f}-{auroc_hi:.3f})  "
              f"AUPRC={auprc:.3f} ({auprc_lo:.3f}-{auprc_hi:.3f})")

        # Persist per-fold OOF predictions for downstream plotting.
        oof_df = pd.DataFrame({"HashID": df["HashID"].values, "y_true": y, "y_score": oof})
        oof_df.to_csv(output_dir / f"oof_{task}_{name}.csv", index=False)

    with open(output_dir / f"metrics_{task}.json", "w") as f:
        json.dump(results, f, indent=2)
    return results


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--features", default="data/features_MGH_deid.csv")
    p.add_argument("--mastersheet", default="data/mastersheet_outcome_deid.xlsx")
    p.add_argument("--labels",
                   default="data/cohort/MGH_dementia_all_04082025_Elissa_rule_made_by_Haoqi.csv",
                   help="Optional BDSPPatientID-keyed dementia diagnosis-date table.")
    p.add_argument("--task", default="all",
                   choices=["all", "DEM_vs_CN", "MCI_vs_CN", "DEMMCI_vs_CN"])
    p.add_argument("--output-dir", default="models/results")
    p.add_argument("--outer-k", type=int, default=5)
    p.add_argument("--inner-k", type=int, default=3)
    p.add_argument("--n-boot", type=int, default=1000)
    p.add_argument("--seed", type=int, default=0)
    args = p.parse_args()

    out = Path(args.output_dir)
    out.mkdir(parents=True, exist_ok=True)

    df = load_data(Path(args.features), Path(args.mastersheet),
                   Path(args.labels) if args.labels else None)
    df = derive_labels(df)
    counts = df["dx_baseline"].value_counts()
    print(f"label counts: {counts.to_dict()}")

    tasks = ["DEM_vs_CN", "MCI_vs_CN", "DEMMCI_vs_CN"] if args.task == "all" else [args.task]
    all_results = {}
    for task in tasks:
        print(f"\n[{task}]")
        sub, y = slice_for_task(df, task)
        all_results[task] = evaluate_task(
            sub, y, task, out,
            outer_k=args.outer_k, inner_k=args.inner_k,
            random_state=args.seed, n_boot=args.n_boot,
        )

    with open(out / "metrics_all.json", "w") as f:
        json.dump(all_results, f, indent=2)
    print(f"\nwrote {out}/metrics_all.json")


if __name__ == "__main__":
    main()
